# torch.Tensor

Los tensores son estructuras de datos que contienen elementos de un único tipo de datos.

In [2]:
import numpy as np
import matplotlib as mpl
import time
import torch

# Inicialización de Tensores

In [3]:
print("+ Inicialización de tensores:")
# Inicialización de un tensor con una lista
t = torch.tensor([[1., -1.], [1., -1.]])
print(f"- Con lista: {t}, dtype: {t.dtype}")

# Inicialización de un tensor con numpy
t = torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))
print(f"- Con numpy: {t}, dtype: {t.dtype}")

+ Inicialización de tensores:
- Con lista: tensor([[ 1., -1.],
        [ 1., -1.]]), dtype: torch.float32
- Con numpy: tensor([[1, 2, 3],
        [4, 5, 6]]), dtype: torch.int64


# Copia y referencia de Tensores

In [4]:
t = torch.randint(0, 100, [10, 15], dtype=torch.uint32) # crea un nuevo tensor
t0 = torch.tensor(t) # copia el tensor
t1 = torch.as_tensor(t) # hace referencia al tensor
print(t)
t.data_ptr(), t0.data_ptr(), t.data_ptr() == t0.data_ptr(), t1.data_ptr(), t.data_ptr() == t1.data_ptr()



tensor([[ 2, 95, 16, 42, 10, 39, 81, 29, 98, 51, 31, 47, 42, 21, 45],
        [56, 11, 23, 44, 50, 53, 71, 14,  6, 81, 85, 34, 72, 72, 90],
        [30, 68, 46, 86, 59, 83, 78, 77,  9, 86, 12, 48, 17, 27, 58],
        [31, 91, 84,  2, 20, 77, 73, 36, 67, 81, 26, 41, 51, 18,  3],
        [72, 30, 60, 97, 50, 34,  8, 18, 67, 52, 71, 67, 81, 27, 13],
        [ 8, 16,  6, 48, 65, 61, 47, 36, 59, 33, 74, 36, 91, 18, 89],
        [25, 46, 59, 74, 20, 29,  8, 75, 40, 39, 85,  6, 84, 48, 50],
        [83, 48, 19,  2, 90, 18, 89, 32, 17, 68, 99, 68, 60, 48, 69],
        [99, 82, 82, 12, 81, 22, 86,  8, 84, 57, 93, 29, 62, 99, 40],
        [47, 27, 81, 94, 12, 74, 43, 42, 52,  0, 49, 72, 15, 18, 39]],
       dtype=torch.uint32)


C:\Users\derli\AppData\Local\Temp\ipykernel_8404\498220540.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  t0 = torch.tensor(t) # copia el tensor


(2813858152448, 2813858153216, False, 2813858152448, True)

In [5]:
data_0 = 1
data_1 = [1, 2, 3]
data_2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
data_3 = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
data_4 = [[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]],
        [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]]
t = torch.tensor(data_2)
t, t.dtype, t.dim(), t.dim_order()


(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.int64,
 2,
 (0, 1))

# Indexing

In [29]:
t = torch.randint(0, 10, [2, 3, 3])
t, t[0][0][1]

(tensor([[[0, 9, 5],
          [7, 4, 4],
          [9, 7, 6]],
 
         [[1, 9, 4],
          [7, 0, 6],
          [2, 3, 3]]]),
 tensor(9))

# Autograd

In [96]:
t = torch.randint(0, 2, [2, 3], requires_grad=True, dtype=torch.float32)
print(t)
out = t.sum()
out.backward()
t.grad

tensor([[1., 0., 1.],
        [0., 1., 0.]], requires_grad=True)


tensor([[1., 1., 1.],
        [1., 1., 1.]])

# Tensor T, Tensor H, Tensor.mT

In [106]:
t = torch.randint(0, 10, [5, 3])
t, t.T, t.H, t.mT

(tensor([[3, 2, 2],
         [0, 1, 9],
         [4, 7, 7],
         [7, 3, 0],
         [5, 1, 5]]),
 tensor([[3, 0, 4, 7, 5],
         [2, 1, 7, 3, 1],
         [2, 9, 7, 0, 5]]),
 tensor([[3, 0, 4, 7, 5],
         [2, 1, 7, 3, 1],
         [2, 9, 7, 0, 5]]),
 tensor([[3, 0, 4, 7, 5],
         [2, 1, 7, 3, 1],
         [2, 9, 7, 0, 5]]))

In [113]:
t_3dim = torch.randn([2, 3, 2])
print(f"Original: {t_3dim}")
try:
    print("T", t_3dim.T)
except:
    print("Operación no valida: T")

try:
    print("H", t_3dim.H)
except:
    print("Operación no valida: H")

t_3dim

Original: tensor([[[-2.9363e-04,  7.2235e-01],
         [-9.6255e-01,  1.0645e+00],
         [ 5.6243e-01,  3.9457e-01]],

        [[ 5.4908e-01, -8.5797e-01],
         [ 2.1150e+00, -4.3458e-01],
         [-6.8356e-01, -2.9142e-01]]])
T tensor([[[-2.9363e-04,  5.4908e-01],
         [-9.6255e-01,  2.1150e+00],
         [ 5.6243e-01, -6.8356e-01]],

        [[ 7.2235e-01, -8.5797e-01],
         [ 1.0645e+00, -4.3458e-01],
         [ 3.9457e-01, -2.9142e-01]]])
Operación no valida: H


C:\Users\derli\AppData\Local\Temp\ipykernel_8404\2273757830.py:4: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\TensorShape.cpp:4416.)
  print("T", t_3dim.T)


tensor([[[-2.9363e-04,  7.2235e-01],
         [-9.6255e-01,  1.0645e+00],
         [ 5.6243e-01,  3.9457e-01]],

        [[ 5.4908e-01, -8.5797e-01],
         [ 2.1150e+00, -4.3458e-01],
         [-6.8356e-01, -2.9142e-01]]])

# Torch.device

In [104]:
t = torch.randint(0, 10, [4, 3]) # tensor creado en cpu
t.device

device(type='cpu')

In [ ]:
t = torch.randint(0, 10, [4, 3], device="cuda") # tensor creado en GPU con CUDA
t.device

device(type='cuda', index=0)

# torch.tensor.new_tensor

In [ ]:
t = torch.randn([2, 4])
t0 = t.new_tensor(torch.randint(0, 10, [2, 3]))
t, t0

C:\Users\derli\AppData\Local\Temp\ipykernel_8404\2735508366.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than tensor.new_tensor(sourceTensor).
  t0 = t.new_tensor(torch.randint(0, 10, [2, 3]))


(tensor([[-0.3601, -0.9362, -0.5876,  0.2867],
         [-0.1367, -1.0925,  1.2141,  1.0626]]),
 tensor([[0., 8., 5.],
         [6., 5., 8.]]))

# torch.tensor -> torch.layout

In [123]:
t = torch.randn([3, 4])
t.layout

torch.strided

# CUDA
Este paquete añade compatibilidad con los tipos de tensores CUDA, que implementan la misma función que los tensores de CPU, pero utilizan GPU para el cálculo.

In [130]:
t = torch.randn([2, 3])
t1 = torch.randn([2, 3], device="cuda")
t.is_cuda, t1.is_cuda

(False, True)