# torch.Tensor

Los tensores son estructuras de datos que contienen elementos de un único tipo de datos.

In [2]:
import numpy as np
import matplotlib as mpl
import time
import torch

# Inicialización de Tensores

In [3]:
print("+ Inicialización de tensores:")
# Inicialización de un tensor con una lista
t = torch.tensor([[1., -1.], [1., -1.]])
print(f"- Con lista: {t}, dtype: {t.dtype}")

# Inicialización de un tensor con numpy
t = torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))
print(f"- Con numpy: {t}, dtype: {t.dtype}")

+ Inicialización de tensores:
- Con lista: tensor([[ 1., -1.],
        [ 1., -1.]]), dtype: torch.float32
- Con numpy: tensor([[1, 2, 3],
        [4, 5, 6]]), dtype: torch.int64


# Copia y referencia de Tensores

In [4]:
t = torch.randint(0, 100, [10, 15], dtype=torch.uint32) # crea un nuevo tensor
t0 = torch.tensor(t) # copia el tensor
t1 = torch.as_tensor(t) # hace referencia al tensor
print(t)
t.data_ptr(), t0.data_ptr(), t.data_ptr() == t0.data_ptr(), t1.data_ptr(), t.data_ptr() == t1.data_ptr()



tensor([[ 2, 95, 16, 42, 10, 39, 81, 29, 98, 51, 31, 47, 42, 21, 45],
        [56, 11, 23, 44, 50, 53, 71, 14,  6, 81, 85, 34, 72, 72, 90],
        [30, 68, 46, 86, 59, 83, 78, 77,  9, 86, 12, 48, 17, 27, 58],
        [31, 91, 84,  2, 20, 77, 73, 36, 67, 81, 26, 41, 51, 18,  3],
        [72, 30, 60, 97, 50, 34,  8, 18, 67, 52, 71, 67, 81, 27, 13],
        [ 8, 16,  6, 48, 65, 61, 47, 36, 59, 33, 74, 36, 91, 18, 89],
        [25, 46, 59, 74, 20, 29,  8, 75, 40, 39, 85,  6, 84, 48, 50],
        [83, 48, 19,  2, 90, 18, 89, 32, 17, 68, 99, 68, 60, 48, 69],
        [99, 82, 82, 12, 81, 22, 86,  8, 84, 57, 93, 29, 62, 99, 40],
        [47, 27, 81, 94, 12, 74, 43, 42, 52,  0, 49, 72, 15, 18, 39]],
       dtype=torch.uint32)


C:\Users\derli\AppData\Local\Temp\ipykernel_8404\498220540.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  t0 = torch.tensor(t) # copia el tensor


(2813858152448, 2813858153216, False, 2813858152448, True)

In [5]:
data_0 = 1
data_1 = [1, 2, 3]
data_2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
data_3 = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
data_4 = [[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]],
        [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]]
t = torch.tensor(data_2)
t, t.dtype, t.dim(), t.dim_order()


(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.int64,
 2,
 (0, 1))

# Indexing

In [29]:
t = torch.randint(0, 10, [2, 3, 3])
t, t[0][0][1]

(tensor([[[0, 9, 5],
          [7, 4, 4],
          [9, 7, 6]],
 
         [[1, 9, 4],
          [7, 0, 6],
          [2, 3, 3]]]),
 tensor(9))

# Autograd

In [96]:
t = torch.randint(0, 2, [2, 3], requires_grad=True, dtype=torch.float32)
print(t)
out = t.sum()
out.backward()
t.grad

tensor([[1., 0., 1.],
        [0., 1., 0.]], requires_grad=True)


tensor([[1., 1., 1.],
        [1., 1., 1.]])

# Tensor T

In [99]:
t = torch.randint(0, 10, [5, 3])
t, t.T

(tensor([[1, 4, 6],
         [5, 9, 8],
         [9, 7, 2],
         [5, 0, 3],
         [8, 0, 7]]),
 tensor([[1, 5, 9, 5, 8],
         [4, 9, 7, 0, 0],
         [6, 8, 2, 3, 7]]))